name: Build and Release

on:
  push:
    tags:
      - 'v*' # This will trigger the workflow when you push a tag that starts with 'v'

jobs:
  build-mac:
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build macOS app
        run: npm run build:mac
        
      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mac-artifacts
          path: |
            dist/*.dmg
            dist/*.zip
  
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build Windows app
        run: npm run build:win
        
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v3
        with:
          name: win-artifacts
          path: |
            dist/*.exe
            dist/*.msi
            dist/*.zip
  
  create-release:
    needs: [build-mac, build-windows]
    runs-on: ubuntu-latest
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/mac-artifacts/**
            artifacts/win-artifacts/**
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
